id: A14C47C9A
title: CI_PÄyantika 2
type: translation
source_metadata:
  languages:
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:37:28.565140
  last_modified_at: 2022-03-01 23:37:28.565143
