id: A14C47C9A
title: CI_Śaikṣa 2
type: translation
source_metadata:
  languages:
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:37:28.695055
  last_modified_at: 2022-03-01 23:37:28.695058
