id: A14C47C9A
title: CI_Adhikaraṇaśamatha 2
type: translation
source_metadata:
  languages:
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:37:28.481550
  last_modified_at: 2022-03-01 23:37:28.481554
