id: A14C47C9A
title: CI_Pāyantika 54
type: translation
source_metadata:
  languages:
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:37:28.609687
  last_modified_at: 2022-03-01 23:37:28.609690
