id: A14C47C9A
title: CI_Pāyantika 61
type: translation
source_metadata:
  languages:
  - zh
  - sa
  datatype: PlainText
  created_at: 2022-03-01 23:37:28.618652
  last_modified_at: 2022-03-01 23:37:28.618655
